### ISSUE TITLE
RegEx Help / Documentation

### ISSUE THREAD

**Issue by derek333x** [whatdaybob/sonarr_youtubedl#19]
I apologize as I didn't know where else to seek help.

I am trying to use sonarr_youtubedl to download a wrestling series weekly show from YouTube.  I believe I just need help with the RegEx to make this work.  The show is in the TVDB.  

Any help would be appreciated. 
Youtube URL:https://www.youtube.com/channel/UCFN4JkGP_bVhAdBsoV9xftA
Episode Patterns in Sonarr: "AEW Dark 98" or "AEW Dark 99"
Episode Patterns in YouTube: "Varsity Blonds, The Acclaimed, Red Velvet, Dark Order, Abadon, Big Swole and More! | AEW Dark, Ep 99"

Log Examples:

2021-07-29 16:56:33,510 - sonarr_youtubedl - DEBUG - [download] "Varsity Blonds, The Acclaimed, Red Velvet, Dark Order, Abadon, Big Swole and More! | AEW Dark, Ep 99" title did not match pattern "AEW\ DARK\ 99"

2021-07-29 17:01:34,165 - sonarr_youtubedl - DEBUG - {'ignoreerrors': True, 'playlistreverse': True, 'matchtitle': 'AEW\\ DARK\\ 99', 'quiet': False, 'logger': <utils.YoutubeDLLogger object at 0x7f649b776410>, 'progress_hooks': [<function ytdl_hooks at 0x7f649b79be60>]},
2021-07-29 17:01:34,164 - sonarr_youtubedl - INFO - AEW Dark missing 1 episodes,
2021-07-29 17:01:34,164 - sonarr_youtubedl - INFO -   1: AEW Dark - AEW Dark 99

Thank you

EDIT: Okay, I did some drastic things to get this to work.  Just in case someone stumbles upon this comment in the future.  I really have no idea why the script was adding in the backslashes to the episode title from Sonarr.  

Here was my new RegEx in the config:
```
series
  - title: 'AEW Dark'
    url: https://www.youtube.com/c/AEW/videos
    regex:
      sonarr:
        match: '\D+'
        replace: 'AEW Dark, Ep '
```

Then I did some drastic work.  In the utils.py file, under "def upperescape(string):" function I commented out everything (except for the return).  That fixed the random backslashes.  I know this is not a proper fix, but it worked for now.  I also know this will get overwritten on an update, but it's a quick fix for me to do again.

**Comment by whatdaybob** [comment]
hi @derek333x sorry on the delay, life!

I had success with the below.

```yaml
    - title: AEW Dark
      url: https://www.youtube.com/c/AEW/videos
      regex:
        sonarr:
          match: '^AEW\sDark\s'
          replace: 'Dark, Ep '
```

issue is that they are not consistant with the naming and the channel doesn't seem to have a playlist so it scans 3000+ videos each time which was a pain to work with.

Below is a user generated playlist that seems to be more reliable with the naming convention though.

```yaml
    - title: AEW Dark
      url: https://www.youtube.com/playlist?list=PLBb_jMbYBIpw2bbakm6Q7cOh9FbMbsWFo
      regex:
        sonarr:
          match: '^AEW\sDark\s'
          replace: 'AEW Dark, Ep '
```

Not sure if it will work with the specials.
