### ISSUE TITLE
Is this really the best solution for regexing?

### ISSUE THREAD

**Issue by Deanosim** [whatdaybob/sonarr_youtubedl#40]
I'm trying to download from https://roosterteeth.com/series/rwby but in Sonarr the episode names are like this `The Shining Beacon (1) The Shining Beacon (2)` and on the site it's `The Shining Beacon The Shining Beacon, Pt.2`
the best solution I could come up with is 
```
    regex:
      sonarr:
        match: '[A-Z][a-z]* [A-Z][a-z]* [A-Z][a-z]* \(1\)'
        replace: 'The Shining Beacon'
        match: '[A-Z][a-z]* [A-Z][a-z]* [A-Z][a-z]* \(2\)'
        replace: 'The Shining Beacon, Pt.2'
        match: '[A-Z][a-z]* [A-Z][a-z]* [A-Z][a-z]* \(1\)'
        replace: 'The First Step'
        match: '[A-Z][a-z]* [A-Z][a-z]* [A-Z][a-z]* \(2\)'
        replace: 'The First Step, Pt.2'
```
But it seems like a pain, have to enter the episode name for every episode, tried entering regex in the replace Field and it just printed the regex
![image](https://user-images.githubusercontent.com/4834976/188888890-4d0d94ef-f08b-4625-8fc3-aa9e57473bb8.png)
